apiVersion: v2
name: stathaus
description: StatHaus - Meter Readings Management PWA
type: application
version: "1.7.3"
appVersion: "1.7.3"
keywords:
  - pwa
  - meter-readings
  - vue
  - nextcloud
  - webdav
home: https://github.com/KallistoX/stathaus
sources:
  - https://github.com/KallistoX/stathaus
maintainers:
  - name: Kallisto
    email: admin@kallisto-app.de
